language: node_js
node_js: 10

# Build CSS and Storybook
script:
  - npm ci
  - npm run bootstrap
  - npm run storybook:build

# Prevent Github Pages from using Jekyll
before_deploy:
  - touch docs/.nojekyll

deploy:
  # Deploy a new version of NPM package and create a Github release
  - provider: script
    skip_cleanup: true
    script:
      - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - npx lerna publish --yes

  # Deploy Storybook to Github Pages
  # See https://docs.travis-ci.com/user/deployment/pages/
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: docs
    on:
      branch: master
